backend:
  name: git-gateway
  
  branch: master

media_folder: src/images
public_folder: /images

collections:
  - name: 'about'
    label: 'About'
    folder: 'src/pages/about'
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "main-pages"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Services'
    folder: 'src/pages/services'
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "main-pages"}
      - { label: 'Body', name: 'body', widget: 'markdown' } 
